### ISSUE TITLE
Fix mobile formatting issue (too much margin on the right)

### ISSUE THREAD

**Issue by coliff** [coliff/caniuse.email#5]

**Comment by CromonMS** [comment]
maybe try bulma.io, nice and simple, minimal styling, which allows for custom colours etc, add table {overflow: auto} and tables work on mobile nicely

**Comment by coliff** [comment]
Looks good. I realised I had already made the site mobile-friendly with some custom CSS to make the table stack the rows so can close this issue now. Im using the new Bootstrap 4 and intend to make use of some of the new features shortly...

**Comment by CromonMS** [comment]
Maybe a little tweaking needed, as there is too much margin on the right still.

![screenshot-caniuse email-2018-01-19-06-48-28-450](https://user-images.githubusercontent.com/5735921/35138145-04390af6-fce5-11e7-8d54-9917d5949e26.png)

**Comment by coliff** [comment]
True dat. I renamed and reopened this issue until I get it fixed. thanks!

**Comment by coliff** [comment]
![caniuse email_ nexus 5x](https://user-images.githubusercontent.com/1212885/40100701-e9997ac2-591f-11e8-9be4-b15e82cb51f0.png)
Should be fine now - finally! Let me know if you have any issues still.
