### ISSUE TITLE
Move all data to external file format (JSON)

### ISSUE THREAD

**Issue by coliff** [coliff/caniuse.email#6]
To improve maintainability

**Comment by jacebenson** [comment]
How do you want this done?
```
{
    "background-color": ['gmail','yahoo','ios','...'],
    "background-image": [],
}

{
  "background-color": [
    {
        "client": "gmail",
        "support": "full"
     },{
        "client": "yahoo",
        "support": "full"
     },{
        "client": "ios",
        "support": "full"
     },{
        "client": "...",
        "support": "full"
     }
  "background-image": [],
}
```

**Comment by jacebenson** [comment]
or more like caniuse.com's data?  https://raw.githubusercontent.com/Fyrd/caniuse/master/fulldata-json/data-2.0.json

**Comment by jacebenson** [comment]
I started to do this on my forked repo, would like your input.  I'm copying a lot of the way caniuse.com has their json file.

**Comment by coliff** [comment]
This looks good, but I'm unsure how the HTML file would pick up the data from the JSON file. Ideally we want the HTML page to rarely change and we just modify the JSON file with any support changes.

**Comment by jacebenson** [comment]
It would require some rewrite of the html and some js to write the tables.  I was working on the data first.
There doesn't seem to be a good way to identify what is supported where.

**Comment by jacebenson** [comment]
I added some parsing code to json.htm... i need to make the table align properly but it takes data fine;
![screenshot-2017-apr-13-258-pm](https://cloud.githubusercontent.com/assets/638764/25022007/e07e5ec6-2059-11e7-8106-74efb2c671d9.png)

**Comment by jacebenson** [comment]
I have this working and would like to merge what i have so someone else could work on the data.json also.
I've left index.htm alone, and made a json.htm to show it working and once the data.json is right, we can remove the index.htm
